	DE2_115_SOPC u0 (
		.altpll_sys                   (<connected-to-altpll_sys>),                   //               c0_out_clk.clk
		.altpll_io                    (<connected-to-altpll_io>),                    //               c2_out_clk.clk
		.c3_out_clk_clk               (<connected-to-c3_out_clk_clk>),               //               c3_out_clk.clk
		.clk_50                       (<connected-to-clk_50>),                       //            clk_50_clk_in.clk
		.reset_n                      (<connected-to-reset_n>),                      //      clk_50_clk_in_reset.reset_n
		.in_port_to_the_key           (<connected-to-in_port_to_the_key>),           //  key_external_connection.export
		.LCD_RS_from_the_lcd          (<connected-to-LCD_RS_from_the_lcd>),          //             lcd_external.RS
		.LCD_RW_from_the_lcd          (<connected-to-LCD_RW_from_the_lcd>),          //                         .RW
		.LCD_data_to_and_from_the_lcd (<connected-to-LCD_data_to_and_from_the_lcd>), //                         .data
		.LCD_E_from_the_lcd           (<connected-to-LCD_E_from_the_lcd>),           //                         .E
		.out_port_from_the_ledg       (<connected-to-out_port_from_the_ledg>),       // ledg_external_connection.export
		.out_port_from_the_ledr       (<connected-to-out_port_from_the_ledr>),       // ledr_external_connection.export
		.altpll_sdram                 (<connected-to-altpll_sdram>),                 //                   pll_c1.clk
		.locked_from_the_pll          (<connected-to-locked_from_the_pll>),          //       pll_locked_conduit.export
		.zs_addr_from_the_sdram       (<connected-to-zs_addr_from_the_sdram>),       //               sdram_wire.addr
		.zs_ba_from_the_sdram         (<connected-to-zs_ba_from_the_sdram>),         //                         .ba
		.zs_cas_n_from_the_sdram      (<connected-to-zs_cas_n_from_the_sdram>),      //                         .cas_n
		.zs_cke_from_the_sdram        (<connected-to-zs_cke_from_the_sdram>),        //                         .cke
		.zs_cs_n_from_the_sdram       (<connected-to-zs_cs_n_from_the_sdram>),       //                         .cs_n
		.zs_dq_to_and_from_the_sdram  (<connected-to-zs_dq_to_and_from_the_sdram>),  //                         .dq
		.zs_dqm_from_the_sdram        (<connected-to-zs_dqm_from_the_sdram>),        //                         .dqm
		.zs_ras_n_from_the_sdram      (<connected-to-zs_ras_n_from_the_sdram>),      //                         .ras_n
		.zs_we_n_from_the_sdram       (<connected-to-zs_we_n_from_the_sdram>),       //                         .we_n
		.SEG7_from_the_seg7           (<connected-to-SEG7_from_the_seg7>),           //         seg7_conduit_end.export
		.in_port_to_the_sw            (<connected-to-in_port_to_the_sw>),            //   sw_external_connection.export
		.usb_conduit_end_DATA         (<connected-to-usb_conduit_end_DATA>),         //          usb_conduit_end.DATA
		.usb_conduit_end_ADDR         (<connected-to-usb_conduit_end_ADDR>),         //                         .ADDR
		.usb_conduit_end_RD_N         (<connected-to-usb_conduit_end_RD_N>),         //                         .RD_N
		.usb_conduit_end_WR_N         (<connected-to-usb_conduit_end_WR_N>),         //                         .WR_N
		.usb_conduit_end_CS_N         (<connected-to-usb_conduit_end_CS_N>),         //                         .CS_N
		.usb_conduit_end_RST_N        (<connected-to-usb_conduit_end_RST_N>),        //                         .RST_N
		.usb_conduit_end_INT0         (<connected-to-usb_conduit_end_INT0>),         //                         .INT0
		.usb_conduit_end_INT1         (<connected-to-usb_conduit_end_INT1>),         //                         .INT1
		.vga_data_CLK                 (<connected-to-vga_data_CLK>),                 //                 vga_data.CLK
		.vga_data_HS                  (<connected-to-vga_data_HS>),                  //                         .HS
		.vga_data_VS                  (<connected-to-vga_data_VS>),                  //                         .VS
		.vga_data_BLANK               (<connected-to-vga_data_BLANK>),               //                         .BLANK
		.vga_data_SYNC                (<connected-to-vga_data_SYNC>),                //                         .SYNC
		.vga_data_R                   (<connected-to-vga_data_R>),                   //                         .R
		.vga_data_G                   (<connected-to-vga_data_G>),                   //                         .G
		.vga_data_B                   (<connected-to-vga_data_B>),                   //                         .B
		.pll_areset_conduit_export    (<connected-to-pll_areset_conduit_export>)     //       pll_areset_conduit.export
	);

